### ISSUE TITLE
[Bug] There is no typing animation when using dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by abhijithbabu** [jason89521/react-typist-component#28]
**Describe the bug**
When using dangerouslySetInnerHTML there is typing animation  

**To Reproduce**
`<span
                                                    className={'pre-line-text'}
                                                    dangerouslySetInnerHTML={{__html: chat.answer}}
                                                ></span>`

**Expected behavior**
Typing animation should still work.

**Comment by jason89521** [comment]
Why would you want to use dangerouslySetInnerHTML instead of directly using children?

**Comment by abhijithbabu** [comment]
I have this string from open ai where it has an identifier for **Product title** which has to be bolded. So i am doing a string replace to <strong>.

**Comment by jason89521** [comment]
It would be advisable to parse the returned value and convert it to a `ReactNode`. Using `dangerouslySetInnerHTML` might not be the most conventional approach in this scenario.
